DATA:
  data_root: /mnt/data/coco
  train_list: ./CELP_CyCTR/lists/coco/train_data_list.txt
  val_list: ./CELP_CyCTR/lists/coco/val_data_list.txt
  classes: 2

TRAIN:
  layers: 50
  sync_bn: False
  train_h: 473
  train_w: 473
  val_size: 473
  hidden_dims: 384
  scale_min: 0.8  # minimum random scale
  scale_max: 1.25 # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  ignore_label: 255
  padding_label: 255
  aux_weight: 1.0
  train_gpu: 0
  workers: 16  # data loader workers
  batch_size: 8  # batch size for training.
  batch_size_val: 1 # this version of code only support val batch = 1
  base_lr: 0.005
  epochs: 50
  start_epoch: 0
  power: 0.9 # 0 means no decay
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 321
  print_freq: 5
  save_freq: 20
  save_path: exp/coco/split0_resnet50/model
  weight:  
  resume:  # path to latest checkpoint (default: none)
  evaluate: True
  split: 0
  shot: 1
  with_transformer: True 
  fix_random_seed_val: True
  warmup: False
  use_coco: True
  use_split_coco: True
  resized_val: True
  ori_resize: True  # use original label for evaluation
